# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='how_angry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='how_happy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='how_sad',
            field=models.FloatField(default=0.0),
        ),
    ]
