# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotions', '0002_auto_20170829_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_sad', models.FloatField(default=0.0)),
                ('how_happy', models.FloatField(default=0.0)),
                ('how_angry', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='how_angry',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='how_happy',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='how_sad',
        ),
        migrations.AddField(
            model_name='vote',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.Tweet'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
