# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_auto_20170907_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='how_angry',
            new_name='acceptance',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='how_happy',
            new_name='admiration',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='how_sad',
            new_name='amazement',
        ),
        migrations.AddField(
            model_name='vote',
            name='anger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='annoyance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='anticipation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='apprehension',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='boredom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='disgust',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='distraction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='ecstasy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='fear',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='grief',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='interest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='joy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='loathing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='pensiveness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='rage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='sadness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='serenity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='surprise',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='terror',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='trust',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vigilance',
            field=models.FloatField(default=0.0),
        ),
    ]
