# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_auto_20171005_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
