# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0005_tweet_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='original_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
