# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0006_auto_20171115_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='acceptance',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='admiration',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='amazement',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='annoyance',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='anticipation',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='apprehension',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='boredom',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='distraction',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='ecstasy',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='grief',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='loathing',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='pensiveness',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='rage',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='serenity',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='terror',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='trust',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vigilance',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='original_text',
            field=models.CharField(max_length=200),
        ),
    ]
