# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0007_auto_20171122_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='anticipation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vote',
            name='trust',
            field=models.FloatField(default=0.0),
        ),
    ]
